### ISSUE TITLE
Is it Real time detection or photo based?

### ISSUE THREAD

**Issue by tarun191997** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#11]
Is it Real time detection or photo-based?

**Comment by Shantanugupta1118** [comment]
It is real-time-based detection.

**Comment by tarun191997** [comment]
can you help me run the program. I don't have nvidea gpu so i am trying to make it run on google colab and it throws an error module 'cv2.dnn' has no attribute 'DNN_BACKEND_CUDA'  and i had also set gpu as hardware accelerator
![Untitled1](https://user-images.githubusercontent.com/44938174/157847542-cdca9f38-4007-49bd-90cd-d60ac784d17c.png)

**Comment by Shantanugupta1118** [comment]
It might not work on collab because most of the functionalities/name in OpenCV is different in Python OpenCV and Google Colab OpenCV
