### ISSUE TITLE
During installing of requirements this is happening at the middle can you please fix the bug and resolve it to me 

### ISSUE THREAD

**Issue by rahulguntu** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#12]
https://user-images.githubusercontent.com/100111606/158216828-799f2d51-f7f5-438b-af37-d97c580090c5.mp4

https://user-images.githubusercontent.com/100111606/158217486-a719ab8e-7dff-4391-8aeb-8dc544513987.mp4

**Comment by Shantanugupta1118** [comment]
Install manually with pip command
