### ISSUE TITLE
please provide a video on this project sir

### ISSUE THREAD

**Issue by GunjiVijayaRaju** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#13]
Shantanu Gupta sir would you please provide a video on this project sir based on how to install the required libraries 
and also how to run this project sir pls make a full length video sir

**Comment by Shantanugupta1118** [comment]
It is not possible yet to reinstall the setup into my device, instead connect with me I'll guide to you and try to setup in your device successfully.

**Comment by SRAVAN332** [comment]
> It is not possible yet to reinstall the setup into my device, instead connect with me I'll guide to you and try to setup in your device successfully.

Hi sir,
Can you please guide me how to setup in my device

**Comment by Shantanugupta1118** [comment]
sure!

**Comment by GunjiVijayaRaju** [comment]
Ok sir
