### ISSUE TITLE
error while running the project

### ISSUE THREAD

**Issue by GunjiVijayaRaju** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#16]
![Screenshot (101)](https://user-images.githubusercontent.com/81728510/174789643-87e138ac-8b62-4c2f-977d-58b8a1f8594b.png)

while running the main.py I got this type of error sir would you please help me sir 

FAILED: fs.is_open(). Can't open "models/deploy.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'

**Comment by Shantanugupta1118** [comment]
Try with install OPENCV by PIP
`pip install opencv-python`
