### ISSUE TITLE
I am getting Assertion failed error in main.py file at 167 th line

### ISSUE THREAD

**Issue by GunjiVijayaRaju** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#17]
![Screenshot (139)](https://user-images.githubusercontent.com/81728510/183915290-75cb26f7-081a-4e33-a5c2-16bf4236982a.png)
 please provide me any solution for this  face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)

**Comment by Shantanugupta1118** [comment]
try to reinstall open-cv by conda command
