### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by shefii02** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#18]
File "C:\Users\Refresh\SDFM\main.py", line 61, in <module>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "C:\Users\Refresh\SDFM\main.py", line 61, in <listcomp>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
![image](https://user-images.githubusercontent.com/115791885/195833027-cd2bdc42-a405-4ed7-9363-f9d6453e7188.png)

**Comment by shefii02** [comment]
all is well 
![thumb-up-female-emoticon-vector-15501930](https://user-images.githubusercontent.com/115791885/195848159-86171886-059f-4d7f-8d15-e2b2bee9a5bc.png)

Thank you for sharing your knowledge

**god bless you**

**Comment by winnk23** [comment]
Hi, i get the same error here. 
May I ask how u solved this?

**Comment by shefii02** [comment]
rewrite
ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]

to=>
ln = [ln[i - 1] for i in net.getUnconnectedOutLayers()]

**Comment by Shantanugupta1118** [comment]
Thanks for this updated solution! I hope it helps a lot. I feel greatful if you give star if you liked the project.
