### ISSUE TITLE
Speed problem

### ISSUE THREAD

**Issue by winnk23** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#20]
Hi @Shantanugupta1118 , 

Can I get your help on the speed problem?
The project is great and all everything is going well, but it's just the speed is very slow or lagging while running. 
What can i do? Thanks.

**Comment by Shantanugupta1118** [comment]
Hi,
Thanks for compliment. But for the Speed or lagging issue, I also have to
do some RND on it. I already tried some other approaches but got accuracy
issues.
If you're doing RND and implementing best approaches on this repo then
please make a pull request too for contribution.

Thanks & Regards
Shantanu Gupta
