### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by rahulguntu** [Shantanugupta1118/Social-Distancing-and-Face-Mask-Detection#9]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
ModuleNotFoundError: No module named 'tensorflow'

This error is displaying while running the program. Could u please solve this

**Comment by Shantanugupta1118** [comment]
Please install the package library Tensorflow.
and follow all instructions given in the readme file.

to install TensorFlow use:
```pip install tensorflow```

in command prompt/ Anaconda Prompt
